# Generated by Django 3.2.16 on 2023-01-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230130_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата публикации комментария', max_length=400, verbose_name='Дата комментария'),
        ),
    ]
